DEFINE OUTPUT PARAMETER op1 AS CHARACTER NO-UNDO.
DEFINE OUTPUT PARAMETER op2 AS CHARACTER NO-UNDO.
DEFINE OUTPUT PARAMETER op3 AS CHARACTER NO-UNDO.

ASSIGN op1 = '{&FILE-NAME}'
       op2 = { foo/foo.i }
	   op3 = { foo/bar.i }.

RETURN '0'.
