RCODE-INFO:FILE-NAME = ENTRY(1, SESSION:PARAMETER, ':').
OUTPUT TO VALUE(ENTRY(2, SESSION:PARAMETER, ':')).
MESSAGE RCODE-INFO:CRC-VALUE.
&IF INTEGER(SUBSTRING(PROVERSION, 1, INDEX(PROVERSION, '.'))) GE 12 &THEN
MESSAGE RCODE-INFO:SIGNATURE-VALUE.
&ELSE
MESSAGE RCODE-INFO:MD5-VALUE.
&ENDIF
OUTPUT CLOSE.
RETURN '0'.