/**
 * Documentation
 * Second line
 */
PROCEDURE internalProc1:

END PROCEDURE.

FUNCTION fooBar RETURNS CHARACER FORWARD.

/* another procedure */
PROCEDURE internalProc2:
  DEFINE INPUT PARAMETER ipPrm1 AS CHARACTER NO-UNDO.
  DEFINE OUTPUT PARAMETER ipPrm2 AS INTEGER NO-UNDO.
  DEFINE INPUT-OUTPUT PARAMETER TABLE FOR ttFooBar.
  
END PROCEDURE.

PROCEDURE internalProc3 PRIVATE:

END PROCEDURE.

FUNCTION fooBar RETURNS CHARACTER:

END FUNCTION.
