MESSAGE "{&FILE-NAME} - LINE 1 - {&LINE-NUMBER}" VIEW-AS ALERT-BOX.
MESSAGE "{&FILE-NAME} - LINE 2 - {&LINE-NUMBER}" VIEW-AS ALERT-BOX.
&IF FALSE &THEN &ENDIF
MESSAGE "{&FILE-NAME} - LINE 4 - {&LINE-NUMBER}" VIEW-AS ALERT-BOX.

