
/*------------------------------------------------------------------------
    File        : InterfaceHeader1
    Purpose     : Purpose of InterfaceHeader1
    Syntax      : 
    Description : Description of InterfaceHeader1
    Author(s)   : Han Solo
    Created     : Tue Dec 31 17:48:48 CET 2019
    Notes       : 
  ----------------------------------------------------------------------*/

USING Progress.Lang.*.

INTERFACE header.InterfaceHeader1: 
    
     
  
    /*------------------------------------------------------------------------------
     Purpose: Purpose of Method1
     Notes: Note of Method1
    ------------------------------------------------------------------------------*/

    METHOD PUBLIC VOID Method1(  ).

END INTERFACE.