DEFINE INPUT PARAMETER pcFile AS CHARACTER NO-UNDO.
RUN prodict/load_df.p (INPUT SESSION:PARAMETER) NO-ERROR.
MESSAGE RETURN-VALUE.
OUTPUT TO VALUE (pcFile).
IF ERROR-STATUS:ERROR OR (RETURN-VALUE NE '':U) THEN
  PUT UNFORMATTED "1" SKIP.
ELSE
  PUT UNFORMATTED "0" SKIP.
OUTPUT CLOSE.
QUIT.
