RUN pct/protoora.p
    (INPUT ENTRY(1, SESSION:PARAMETER, ';':U),
     INPUT ENTRY(2, SESSION:PARAMETER, ';':U),
     INPUT ENTRY(3, SESSION:PARAMETER, ';':U),
     INPUT ENTRY(4, SESSION:PARAMETER, ';':U),
     INPUT INTEGER(ENTRY(5, SESSION:PARAMETER, ';':U))).