DEFINE OUTPUT PARAMETER prm1 AS CHAR NO-UNDO.
DEFINE OUTPUT PARAMETER prm2 AS CHAR NO-UNDO.
DEFINE OUTPUT PARAMETER prm3 AS CHAR NO-UNDO.
DEFINE OUTPUT PARAMETER prm4 AS CHAR NO-UNDO.
ASSIGN prm1 = "PCT1"
       prm2 = "PCT2"
       prm3 = "PCT3"
       prm4 = "PCT4".
RETURN "0".
