/*************************************************************/
 /* Copyright (c) 2012 by progress Software Corporation.      */
 /*                                                           */
 /* all rights reserved.  no part of this program or document */
 /* may be  reproduced in  any form  or by  any means without */
 /* permission in writing from progress Software Corporation. */
 /*************************************************************/
/*------------------------------------------------------------------------
    Purpose     : Wrapper for data admin .d import of sequence values
    Syntax      : 
    Description : 
    Author(s)   : hdaniels
    Created     : Mar 31 2012  
    Notes       : 
  ----------------------------------------------------------------------*/

using Progress.Lang.*.
using OpenEdge.DataAdmin.Util.ISequenceUtility .

interface OpenEdge.DataAdmin.Internal.Util.ISequenceImportUtility inherits ISequenceUtility:  
     
end interface.