  FIND FIRST _File WHERE _File._File-Name EQ ENTRY(1, SESSION:PARAMETER, ",") NO-LOCK NO-ERROR.
  IF (AVAILABLE _File) THEN DO:
    FIND FIRST _Index WHERE _Index._File-recid EQ RECID(_File) AND _Index._Index-Name EQ ENTRY(2, SESSION:PARAMETER, ",") NO-LOCK NO-ERROR.
    RETURN (IF AVAILABLE _Index THEN "0" ELSE "2").
  END.
  ELSE RETURN "1".
