using Progress.Lang.*.

class eu.rssw.pct.Z inherits eu.rssw.pct.Y implements eu.rssw.pct.A, eu.rssw.pct.B:
  constructor public Z():
  end constructor.

  method public override void method1() :

  end method.

  /* 
   * My Comment 01
   * Hello world
   */
  method public void method2() :
   /* My second comment */
  end method.
  
  /* 
   * My Comment 02
   * Hello world
   */
  method public void method2(input-output foo as char, input dataset-handle ds1) :
   /* My second comment */
  end method.

end class.
