name: WikiAltPush

# https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#gollum
on:
  gollum:

jobs:
  update-remote-wiki:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
      with:
          repository: 'Riverside-Software/pct.wiki'
          ref: 'master'
          fetch-depth: '0'

    # https://stackoverflow.com/questions/64270867/auth-error-trying-to-copy-a-repo-with-github-actions
    - name: Clean Auth header
      run: git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | xargs -L1 git config --unset-all

    - name: Push to alternate repo
      run: git remote add upstream https://gquerret:$GH_PAT@github.com/Riverside-Software/pct-wiki && git push -u upstream master
      env:
        GH_PAT: ${{ secrets.GIT_ACCESS_TOKEN }}
